server:
    port: 80
    
spring:
    application:
        name: sale-management-service
    profiles:
        active: default
    cloud:
        config:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fatchRegistry: true
        serviceUrl:
            defaultZone: http://103.13.231.22:8761/eureka/
        
        
        
        
        
        
        